name: Lint Workflow
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1
  dockerfile-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hadolint
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  super-linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
